#--------------------------------------------------------------------
#
# Azure Example - Build
#
#--------------------------------------------------------------------

name: Build

on:
    workflow_dispatch:
    push:
      branches: [ development, main, release/* ]
      
jobs:

    build:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ ubuntu-latest ]
            java: [17]
 
        steps:

        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Set up Java 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: 'maven'
            
        - name: Cache local Maven repository
          uses: actions/cache@v3
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
              ${{ runner.os }}-maven-

        - name: Build with Maven
          run: mvn -e -U clean install
